version: '3'

services:
  user-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zambila2011!
      POSTGRES_DB: dsprjmerge
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


  user-microservice:
    image: backend-user
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/dsprjmerge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Zambila2011!
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8080:8080"
    depends_on:
      - user-db
  

volumes:
  db-data:

